# -*- coding: utf-8 -*-
"""similar_user_recommendation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1--vdx2CEg05VCwXrGZedN8WRTQQm-OTT
"""

# 유저 특성 뽑기 -> 나랑 비슷한 사람들 -> 나랑 비슷한 사람들이 푼 문제 중 안푼문제 추천

from google.colab import drive
drive.mount('/gdrive')

import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import os
import json
# import pymysql
from sklearn.neighbors import NearestNeighbors
# from .preprocess import load_data, preprocess_rival
import warnings
warnings.filterwarnings("ignore")

def remove_self(x):
    if x[0] in x[1]:
        return np.delete(x[1],np.where(x[0]==x[1])[0])
    else:
        return x[1][:6]


def rival_knn_main():
    # df_problems, df_problems_solved, df_users, df_problems_class= load_data(db)
    df_data = pd.read_csv('/gdrive/My Drive/Colab Notebooks/SSAFY/dataRecommendation/user_avg_level_of_tags_.csv')
    print('데이터 로드 완료!')
    # df_data= preprocess_rival(df_problems_solved,df_problems,df_users)
    print('데이터 전처리 완료!')
    knn = NearestNeighbors(n_neighbors=7, p=1)
    data= np.array(df_data.iloc[:,3:])
    knn.fit(data)
    rival_idx= knn.kneighbors(data, return_distance=False)
    print('knn 학습 수행 완료!')
    result=([[k,v] for k,v in zip(list(range(len(rival_idx))),rival_idx)])
    df_result= pd.DataFrame(result)
    df_result[1]= df_result.apply(remove_self, axis=1)
    df_result= df_result[1]
    lst_rivals= [','.join(list(df_data['handle'].iloc[x].values)) for x in df_result]
    target_users= list(df_data.handle)

    output = pd.DataFrame(target_users, columns=['handle'])
    output['similar_rivals'] = lst_rivals
    output.index += 1  #mysql에서 auto increment를 위해 1 추가
    output.index.name='id'
    output.to_csv('/gdrive/My Drive/Colab Notebooks/SSAFY/dataRecommendation/similar_rival_knn.csv')

    print('라이벌 추천 완료!')
    return output

rival_knn_main()